/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.cts.pnrservice.api;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import com.cts.pnrservice.model.CreatePnrFault;
import com.cts.pnrservice.model.CreatePnrRequest;
import com.cts.pnrservice.model.CreatePnrResponse;

import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-01-16T07:29:02.569Z")

@Api(value = "createPnr", description = "the createPnr API")
public interface CreatePnrApi {

    @ApiOperation(value = "Operation CreatePnr", notes = "", response = CreatePnrResponse.class, tags={ "Pnr", })
    @ApiResponses(value = { 
        @ApiResponse(code = 500, message = "", response = CreatePnrFault.class),
        @ApiResponse(code = 200, message = "", response = CreatePnrResponse.class) })
    
    @RequestMapping(value = "/createPnr",
        produces = { "application/xml", "application/json" }, 
        consumes = { "application/xml", "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<CreatePnrResponse> createPnr(@ApiParam(value = "" ,required=true )  @Valid @RequestBody CreatePnrRequest body);

}
